


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch


stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  analysis:
    cmd: python3 -u rank-along-time-analysis.py
    deps:
      - rank-along-time-analysis.py
      - data/raw-area-responses/
    params:
      - load
      - preprocess
      - rrr
      - rrr-param-search
    outs:
      - results/max-ranks.pickle
  plots:
    cmd: python3 -u rank-along-time-plot.py
    deps:
      - rank-along-time-plot.py
      - results/max-ranks.pickle
    params:
      - preprocess
    outs:
      - figures/max-ranks.png