


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch


stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  analysis:
    cmd: python3 -u time-lag-search-analysis.py
    deps:
      - time-lag-search-analysis.py
      - data/raw-area-responses/
    params:
      - load
      - preprocess
      - rrr
      - rrr-param-search
      - best-rrr-params
    outs:
      - results/time-lag-search.pickle
  plots:
    cmd: python3 -u time-lag-search-plot.py
    deps:
      - time-lag-search-plot.py
      - results/time-lag-search.pickle
    params:
      - rrr-param-search
    outs:
      - figures/time-lag-search.png