


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch


stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  analysis:
    cmd: python3 -u lag-along-time-analysis.py
    deps:
      - lag-along-time-analysis.py
      - data/raw-area-responses/
    params:
      - load
      - preprocess
      - rrr
      - rrr-param-search
      - best-rrr-params
    outs:
      - results/lags-along-time.pickle
      - results/max-lags-along-time.pickle
  imshow:
    cmd: python3 -u lags-along-time-plot.py
    deps:
      - lags-along-time-plot.py
      - results/lags-along-time.pickle
    params:
      - preprocess
      - rrr-param-search
    outs:
      - figures/lags-along-time.png
  plot:
    cmd: python3 -u max-lags-along-time-plot.py
    deps:
      - max-lags-along-time-plot.py
      - results/max-lags-along-time.pickle
    params:
      - preprocess
      - rrr-param-search
    outs:
      - figures/max-lags-along-time.png