


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  preprocess:
    cmd: python3 -u preprocessing.py
    deps:
      - preprocessing.py
      - data/raw-area-responses/
    params:
      - preprocess
    outs:
      - data/area-responses/
  analysis:
    cmd: python3 -u cv-time-lag-analysis.py
    deps:
      - cv-time-lag-analysis.py
      - data/raw-area-responses/
    params:
      - load
      - preprocess
      - rrr
      - rrr-param-search
    outs:
      - results/CV-lag-time.pickle
  plots:
    cmd: python3 -u cv-time-lag-plot.py
    deps:
      - cv-time-lag-plot.py
      - results/CV-lag-time.pickle
    params:
      - preprocess
      - rrr-param-search
    outs:
      - figures/CV-timelag.png