


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  preprocess:
    cmd: python3 -u preprocessing.py
    deps:
      - preprocessing.py
      - data/raw-area-responses/
    params:
      - preprocess
    outs:
      - data/area-responses/
  analysis:
    cmd: python3 -u rrr-score-time.py
    deps:
      - rrr-score-time.py
      - data/area-responses/
    params:
      - preprocess
      - rrr
    outs:
      - results/rrr-score-time.pickle
  plots:
    cmd: python3 -u rrr-score-time-plot.py
    deps:
      - rrr-score-time-plot.py
      - results/rrr-score-time.pickle
    params:
      - preprocess
    outs:
      - figures/rrr-score-time.png