


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  preprocess:
    cmd: python3 -u preprocessing.py
    params:
      - preprocess
    outs:
      - data/area-responses/
  rrr_analysis:
    cmd: python3 -u rrr_analysis.py
    deps:
      - data/area-responses/
    params:
      - cache
      - rrr
    outs:
      - results/rrr_coefficients.pickle
  plots:
    cmd: python3 -u rrr_plot.py
    deps:
      - results/rrr_coefficients.pickle
    params:
      - rrr
    outs:
      - figures/VISl-VISp_rrr-coefficients.png