


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  preprocess:
    cmd: python3 -u preprocessing.py
    deps:
      - data/raw-area-responses/
      - preprocessing.py
    params:
      - cache
      - preprocess
    outs:
      - data/area-responses/
  analysis:
    cmd: python3 -u time_lag_analysis.py
    deps:
      - data/area-responses/
      - time_lag_analysis.py
    params:
      - preprocess
      - rrr
    outs:
      - results/VISp_VISl_cross-time-coeffs.pickle
      - results/VISp_VISl_cross-time-lag.pickle
  plots:
    cmd: python3 -u time_lag_plot.py
    deps:
      - results/VISp_VISl_cross-time-coeffs.pickle
      - time_lag_plot.py
    params:
      - preprocess
    outs:
      - figures/Time_lag_between_V1_LM.png