


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  preprocess:
    cmd: python3 -u preprocessing.py
    params:
      - cache
      - preprocess
    outs:
      - data/area-responses/
  analysis:
    cmd: python3 -u rrr-rank-analysis.py
    deps:
      - data/area-responses/
    params:
      - preprocess
      - rrr
    outs:
      - results/VISp_VISl_cross-time-test-scores.pickle
  plots:
    cmd: python3 -u rrr-rank-plot.py
    deps:
      - results/VISp_VISl_cross-time-test-scores.pickle
    params:
      - preprocess
      - rrr
      - rrr-plot
    outs:
      - figures/V1-V2_cross-time_RRR-rank-analysis-2DIM.png
      - figures/V1-V2_cross-time_RRR-rank-analysis-timewise.png
      - figures/V1-V2_cross-time_RRR-rank-analysis-averaged-over-time.png