


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  preprocess:
    cmd: python3 -u preprocessing.py
    deps:
      - preprocessing.py
    params:
      - preprocess
    outs:
      - data/area-responses/
  behav-preprocess:
    cmd: python3 -u behav-preprocessing.py
    deps:
      - behav-preprocessing.py
    params:
      - preprocess
    outs:
      - data/behav-responses/
  analysis:
    cmd: python3 -u control-models.py
    deps:
      - control-models.py
      - data/area-responses/
      - data/behav-responses/
    params:
      - preprocess
      - rrr
    outs:
      - figures/control-models.png