


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch

stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  preprocess:
    cmd: python3 -u preprocessing.py
    deps:
      - data/raw-area-responses/
      - preprocessing.py
    params:
      - cache
      - preprocess
    outs:
      - data/area-responses/
  analysis:
    cmd: python3 -u cv-rank-cross-time.py
    deps:
      - data/area-responses/
      - cv-rank-cross-time.py
    params:
      - preprocess
      - rrr
    outs:
      - figures/CV-rank_cross-time.png