


metrics:
  - metrics.json

params:
  - params.yaml

plots:
  - plot.csv:
      y: accuracy
      x: epoch



# MARK: Crosstest

stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    deps:
      - load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  analysis:
    cmd: python3 -u crosstime-analysis.py
    deps:
      - crosstime-analysis.py
      - data/raw-area-responses/
    params:
      - load
      - preprocess
      - rrr
      - best-rrr-params
      - rrr-param-search
      - crosstime
    outs:
      - results/cross-time-RRR.pickle
  plots:
    cmd: python3 -u crosstime-plot.py
    deps:
      - crosstime-plot.py
      - results/cross-time-RRR.pickle
    params:
      - rrr-param-search
    outs:
      - figures/cross-time-RRR.png



# MARK: time-slice

# stages:
#   load:
#     cmd: python3 -u load_raw_activity_data.py
#     deps:
#       - load_raw_activity_data.py
#     params:
#       - load
#     outs:
#       - data/raw-area-responses/
#   preprocess:
#     cmd: python3 -u preprocessing.py
#     deps:
#       - preprocessing.py
#       - data/raw-area-responses/
#     params:
#       - load
#       - preprocess
#     outs:
#       - data/area-responses/
#   analysis:
#     cmd: python3 -u rrr-time-slice-analysis.py
#     deps:
#       - rrr-time-slice-analysis.py
#       - data/area-responses/
#     params:
#       - rrr-time-slice
#       - load
#       - best-rrr-params
#     outs:
#       - results/rrr-time-slice.pickle
#   plots:
#     cmd: python3 -u rrr-time-slice-plot.py
#     deps:
#       - rrr-time-slice-plot.py
#       - results/rrr-time-slice.pickle
#     params:
#       - preprocess
#     outs:
#       - figures/rrr-time-slice.png