stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  # preprocess:
  #   cmd: python3 -u preprocess_data.py
  #   deps:
  #     - preprocess_data.py
  #     - data/raw-area-responses/
  #   params:
  #     - preprocess
  #   outs:
  #     - data/preprocessed-area-responses/
  analysis:
    cmd: python3 -u cv-time-lag-analysis.py
    deps:
      - cv-time-lag-analysis.py
      - data/raw-area-responses/
    params:
      - load
      - preprocess
      - rrr
      - rrr-param-search
    outs:
      - results/CV-lag-time.pickle
  plots:
    cmd: python3 -u cv-time-lag-plot.py
    deps:
      - cv-time-lag-plot.py
      - results/CV-lag-time.pickle
    params:
      - preprocess
      - rrr
      - rrr-param-search
    outs:
      - figures/rrr-param-search.png