stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  layer-assignment:
    cmd: python3 -u layer-assignment-analysis.py
    deps:
      - layer-assignment-analysis.py
      - data/ccf_volumes/
    params:
      - load
    outs:
      - data/units/
  analysis:
    cmd: python3 -u layer-interaction-analysis.py
    deps:
      - layer-interaction-analysis.py
      - data/units/
    params:
      - load
      - crosstime
    outs:
      - results/layer-interaction_V1-to-LM.pickle
      - results/layer-interaction_LM-to-V1.pickle
  plots:
    cmd: python3 -u layer-interaction-plot.py
    deps:
      - layer-interaction-plot.py
      - data/units/
    params:
      - load
      - preprocess
      - crosstime
    outs:
      - figures/layer-interaction_V1-to-LM.png
      - figures/layer-interaction_LM-to-V1.png