stages:
  load:
    cmd: python3 -u load_raw_activity_data.py
    params:
      - load
    outs:
      - data/raw-area-responses/
  preprocess:
    cmd: python3 -u preprocessing.py
    deps:
      - preprocessing.py
      - data/raw-area-responses/
    params:
      - preprocess
    outs:
      - data/area-responses/
  analysis:
    cmd: python3 -u layer-rank-analysis.py
    deps:
      - layer-rank-analysis.py
      - analyses/layer_rank.py
      - data/area-responses/
      - data/units/
    params:
      - load
      - preprocess
      - layer-rank
    outs:
      - results/layer-rank.pickle
  plot:
    cmd: python3 -u layer-rank-plot.py
    deps:
      - layer-rank-plot.py
      - results/layer-rank.pickle
    params:
      - preprocess
    outs:
      - figures/layer-rank.png