site_name: Allen Project Documentation

theme:
  name: readthedocs # or material 

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          selection:
            new_path_syntax: true

nav:
  - Home: index.md
  - DVC Framework: DVC.md
  - Experiment History: notion/Allen project d3cfe5aab8384495b58fba8a47eeadcc.md
  - References:
    - Overview: references/references.md
    - Experiment Modules:
      - references/experiments/layer-rank.md
      - references/experiments/layer-interaction.md
      - references/experiments/rank-along-time.md
