site_name: Allen Project Documentation

theme:
  name: readthedocs # or material 

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          selection:
            new_path_syntax: true

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
#  - About: about.md
#  - Getting Started:
#      - Installation: getting-started/installation.md
#      - Configuration: getting-started/configuration.md
#  - User Guide:
#      - Features: user-guide/features.md
#      - FAQ: user-guide/faq.md
