
cache:
  location: "data/.vbn_s3_cache"
  force_download: False

neuropixel:
  area_of_interest: "VISpm"
  block: "active behavior"

preprocess:
  areas: ["VISp", "VISl"]
  stimulus-block: 4
  # Stimulus blocks:
  # 0: change detection task
  # 2: receptive field mapping by gabor stimuli
  # 4: full-flash
  # 5: passive replay
  bin-size: 0.050
  stimulus-duration: 0.250

cca:
  cv: 5
  n_components: 2
  scoring: 'r2'

rrr:
  cv: 5
  rank: 10