
cache:
  location: "data/.vbn_s3_cache"
  force_download: False

neuropixel:
  area_of_interest: "VISpm"
  block: "active behavior"

load:
  session: 1108334384
  areas: ["VISp", "VISl"] # "VISpm" # "VISm" has no spikes
  stimulus-block: 5
  # Stimulus blocks:
  # 0: change detection task
  # 2: receptive field mapping by gabor stimuli
  # 4: full-flash
  # 5: passive replay
  step-size: 0.001 # in seconds
  stimulus-duration: 0.250 # in seconds

preprocess:
  areas: ["VISp", "VISl"] # "VISpm" # "VISm" has no spikes
  lag-time: 0 # in milliseconds
  lag-area: ""
  step-size: 0.050 # time-step in seconds # 0.010
  bin-size: 0.050 # time-window in seconds # Joao's default: 0.100
  stimulus-duration: 0.250 # in seconds

cca:
  cv: 5
  n_components: 2
  scoring: 'r2'

rrr:
  cv: 3
  rank: 18
  error-score: 'raise'
  predictor: 'VISp'
  target: 'VISl'
  timepoint: 0.050 # in seconds
  sample-size: 15 # under-sampling size

rrr-time-slice:
  predictor-time: [.060, .090, .120, .150] # in seconds

crosstime:
  scaling-factor: 10 # in ms

rrr-param-search:
  cv: [2,3,4] # [3]
  rank: [2,4,6,8,10,12,14,16,18,20,25,30] # [14]
  lag: [0,2] # [100,105,110,115,120,125,130,135,140,145,150]
  timepoints: [0,50,100,150] # [0]
  # duration: 0.250
  # time-bin: 0.050
  # time-step: 0.025

interaction-layers:
  V1:
    input: [5] # [1, 2]
    output: [2] # 2 is 2/3
  LM:
    input: [4]
    output: [6] # [2]
