
cache:
  location: "data/.from_warehouse"
  force_download: False

neuropixel:
  area_of_interest: "VISpm"
  block: "active behavior"

load:
  session: 0
  areas: ["VISp", "VISl"] # "VISpm" # "VISm" has no spikes
  stimulus-block: 'natural_scenes'
  step-size: 0.001 # in seconds
  stimulus-duration: .25 # in seconds

preprocess:
  areas: ["VISp", "VISl"] # "VISpm" # "VISm" has no spikes
  lag-time: 0 # in milliseconds
  lag-area: ""
  step-size: 0.050 # time-step in seconds # 0.010
  bin-size: 0.050 # time-window in seconds # Joao's default: 0.100
  stimulus-duration: .25 # in seconds

cca:
  cv: 5
  n_components: 2
  scoring: 'r2'

rrr:
  cv: 3
  rank: 18
  error-score: 'raise'
  predictor: 'VISp'
  target: 'VISl'
  timepoint: 0.050 # in seconds
  sample-size: 15 # under-sampling size

rrr-time-slice:
  predictor-time: [.060, .090, .120, .150] # in seconds

crosstime:
  scaling-factor: 10 # in ms

rrr-param-search:
  cv: [2,4,6,8,10] # [3]
  rank: [5,10,15,20,25] # [14]
  lag: [0,1] # [100,105,110,115,120,125,130,135,140,145,150]
  timepoints: [0,50,100,150] # [0]
  # duration: 0.250
  # time-bin: 0.050
  # time-step: 0.025

layer-rank:
  cv: [2,3,4,5,6,7,8,9,10]
  bestRank: 15
  minRank: 5
  maxRank: 25
  stepRank: 1
  timepoint: 100 # in milliseconds

interaction-layers:
  V1:
    input: [5] # [1, 2]
    output: [2] # 2 is 2/3
  LM:
    input: [4]
    output: [6] # [2]
