
cache:
  location: "data/.vbn_s3_cache"
  force_download: False

neuropixel:
  area_of_interest: "VISpm"
  block: "active behavior"

preprocess:
  areas: ["VISp", "VISl"] # "VISpm" # "VISm" has no spikes
  stimulus-block: 5
  # Stimulus blocks:
  # 0: change detection task
  # 2: receptive field mapping by gabor stimuli
  # 4: full-flash
  # 5: passive replay
  raw-step-size: 0.005 # in seconds
  step-size: 0.025 # in seconds
  bin-size: 0.050 # in seconds # Joao's default: 0.100
  stimulus-duration: 0.250 # in seconds

cca:
  cv: 5
  n_components: 2
  scoring: 'r2'

rrr:
  cv: 3
  rank: 8
  error-score: 'raise'

rrr-plot:
  discard-first-500-ms: True

rrr-cv-rank-time:
  cv: [2,3,4,5,6]
  ranks: [3,4,5,6,7,8,9,10,11,12,13,14]
  duration: 0.250
  time-bin: 0.050
  time-step: 0.025